CREATE TABLE [dbo].[ParkingRegistration]
(
	[Id]             SMALLINT NOT NULL PRIMARY KEY,
	[UFId]           INT FOREIGN KEY REFERENCES Registrant(Id) NOT NULL,
	[TagNumber]      NVARCHAR (20) NULL,
	[DateTagIssued]  SMALLDATETIME NULL,
	[IssuedBy]       NVARCHAR (20)  NULL,
	[Phone]          NVARCHAR (20)  NULL,
	[Make]			 NVARCHAR (20)  NULL,
	[Model]			 NVARCHAR (20)  NULL,
	[Year]			 SMALLINT      NULL,
	[Color]          NVARCHAR (20)  NULL,
	[LicenseNumber]  NVARCHAR (20)  NULL,
	[State]          NVARCHAR (10)  NULL,
	[CreatedDate]    SMALLDATETIME      NULL,
	[ModifiedDate]   SMALLDATETIME      NULL,
	[IsStudent]		 BIT NOT NULL,
	[IsFacStaff]     BIT NOT NULL,
	[ViolationCount] TINYINT  CONSTRAINT [DF_ParkingRegistration_ViolationCount] DEFAULT ((0)) NULL,
	[Location]       TINYINT FOREIGN KEY REFERENCES Location(Id) NULL,
	[ClassYear]      TINYINT FOREIGN KEY REFERENCES ClassYear(Id) NULL,
	[StudentType]    TINYINT FOREIGN KEY REFERENCES StudentType(Id) NULL,
	[VehicleType]    TINYINT FOREIGN KEY REFERENCES  VehicleType(Id) NOT NULL,
	CONSTRAINT [PK_ParkingRegistration] PRIMARY KEY CLUSTERED ([Id] ASC)
)
